<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.xiangganluo</groupId>
        <artifactId>flexpoint-plugin-all</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>flexpoint-plugin-metrics</artifactId>
    <name>Flex Point Plugin - Metrics Summary</name>
    <description>官方插件：指标汇总（周期输出调用统计）</description>

    <dependencies>
        <dependency>
            <groupId>io.github.xiangganluo</groupId>
            <artifactId>flexpoint-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>