server:
  port: 8080

spring:
  application:
    name: flexpoint-spring-boot-example
  
# 日志配置
logging:
  level:
    com.flexpoint: DEBUG
    org.springframework.boot: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# FlexPoint 配置
flexpoint:
  enabled: true
  monitor:
    enabled: true
    log-invocation: true
  registry:
    enabled: true
    allow-duplicate-registration: false
#  selector:
#    chains:
#      default-selector-chain:
#        - codeVersionSelector