server:
  port: 8080

spring:
  application:
    name: flexpoint-spring-boot-example

logging:
  level:
    com.flexpoint: DEBUG
    com.flexpoint.example.springboot: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Flex Point框架配置
flexpoint:
  # 是否启用Flex Point框架
  enabled: true