<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.xiangganluo</groupId>
        <artifactId>flexpoint-examples</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>java-example</artifactId>
    <name>Flex Point Java Example</name>
    <description>Java原生环境下的Flex Point用法示例</description>
    <dependencies>
        <dependency>
            <groupId>io.github.xiangganluo</groupId>
            <artifactId>flexpoint-core</artifactId>
        </dependency>
        <!-- 官方选择器插件（Code+Version） -->
        <dependency>
            <groupId>io.github.xiangganluo</groupId>
            <artifactId>flexpoint-plugin-selector-code-version</artifactId>
        </dependency>
    </dependencies>
</project> 