<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.xiangganluo</groupId>
        <artifactId>flexpoint-plugin-all</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>flexpoint-plugin-selector-code-version</artifactId>
    <name>Flex Point Plugin - Code Version Selector</name>
    <description>官方插件：Code + Version 选择器（依赖 Code 选择器）</description>

    <dependencies>
        <dependency>
            <groupId>io.github.xiangganluo</groupId>
            <artifactId>flexpoint-plugin-selector-code</artifactId>
        </dependency>
    </dependencies>
</project>
